#!/bin/bash
#PBS -N xxx
#PBS -l select=6:ncpus=128:mpiprocs=128
#PBS -l walltime=12:00:00
#PBS -A WYOM0200
#PBS -j oe
#PBS -q main

module --force purge
module load ncarenv/23.06
module load intel-classic/2023.0.0
module load hdf5/1.12.2
module load cray-mpich/8.1.25
module load ncview/2.1.8
module load craype/2.7.20
module load netcdf/4.9.2
module load ncarcompilers/1.0.0
